aws_region           = "eu-west-2"
project_name         = "contact-centre-ai-poc"
dynamodb_table_name  = "ContactCentreCases"
lambda_function_name = "lex_orchestrator"
bedrock_model_id     = "global.amazon.nova-2-lite-v1:0"